#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMMODELWEB.Module
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MML_AX_LIVE")]
	public partial class DBModuleWebDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMPM_USER(MPM_USER instance);
    partial void UpdateMPM_USER(MPM_USER instance);
    partial void DeleteMPM_USER(MPM_USER instance);
    partial void InsertMPM_DOORPRIZE(MPM_DOORPRIZE instance);
    partial void UpdateMPM_DOORPRIZE(MPM_DOORPRIZE instance);
    partial void DeleteMPM_DOORPRIZE(MPM_DOORPRIZE instance);
    partial void InsertMPM_DOORPRIZE_USER(MPM_DOORPRIZE_USER instance);
    partial void UpdateMPM_DOORPRIZE_USER(MPM_DOORPRIZE_USER instance);
    partial void DeleteMPM_DOORPRIZE_USER(MPM_DOORPRIZE_USER instance);
    #endregion
		
		public DBModuleWebDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AX_LIVE"].ConnectionString, mappingSource)
        {
			OnCreated();
		}
		
		public DBModuleWebDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBModuleWebDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBModuleWebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBModuleWebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MPM_USER> MPM_USERs
		{
			get
			{
				return this.GetTable<MPM_USER>();
			}
		}
		
		public System.Data.Linq.Table<MPM_DOORPRIZE> MPM_DOORPRIZEs
		{
			get
			{
				return this.GetTable<MPM_DOORPRIZE>();
			}
		}
		
		public System.Data.Linq.Table<MPM_DOORPRIZE_USER> MPM_DOORPRIZE_USERs
		{
			get
			{
				return this.GetTable<MPM_DOORPRIZE_USER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MPM_USER")]
	public partial class MPM_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NPK;
		
		private string _DOMAIN;
		
		private string _USER_ID;
		
		private string _USER_NAME;
		
		private string _DATAAREA_ID;
		
		private string _MAIN_DEALER_ID;
		
		private string _SITE_ID_MAPPING;
		
		private string _IS_ACTIVE;
		
		private string _CREATE_BY;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private string _MODIF_BY;
		
		private System.Nullable<System.DateTime> _MODIF_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNPKChanging(string value);
    partial void OnNPKChanged();
    partial void OnDOMAINChanging(string value);
    partial void OnDOMAINChanged();
    partial void OnUSER_IDChanging(string value);
    partial void OnUSER_IDChanged();
    partial void OnUSER_NAMEChanging(string value);
    partial void OnUSER_NAMEChanged();
    partial void OnDATAAREA_IDChanging(string value);
    partial void OnDATAAREA_IDChanged();
    partial void OnMAIN_DEALER_IDChanging(string value);
    partial void OnMAIN_DEALER_IDChanged();
    partial void OnSITE_ID_MAPPINGChanging(string value);
    partial void OnSITE_ID_MAPPINGChanged();
    partial void OnIS_ACTIVEChanging(string value);
    partial void OnIS_ACTIVEChanged();
    partial void OnCREATE_BYChanging(string value);
    partial void OnCREATE_BYChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnMODIF_BYChanging(string value);
    partial void OnMODIF_BYChanged();
    partial void OnMODIF_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIF_DATEChanged();
    #endregion
		
		public MPM_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPK", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NPK
		{
			get
			{
				return this._NPK;
			}
			set
			{
				if ((this._NPK != value))
				{
					this.OnNPKChanging(value);
					this.SendPropertyChanging();
					this._NPK = value;
					this.SendPropertyChanged("NPK");
					this.OnNPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN", DbType="NVarChar(30)")]
		public string DOMAIN
		{
			get
			{
				return this._DOMAIN;
			}
			set
			{
				if ((this._DOMAIN != value))
				{
					this.OnDOMAINChanging(value);
					this.SendPropertyChanging();
					this._DOMAIN = value;
					this.SendPropertyChanged("DOMAIN");
					this.OnDOMAINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this.OnUSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_NAME = value;
					this.SendPropertyChanged("USER_NAME");
					this.OnUSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAAREA_ID", DbType="NVarChar(4)")]
		public string DATAAREA_ID
		{
			get
			{
				return this._DATAAREA_ID;
			}
			set
			{
				if ((this._DATAAREA_ID != value))
				{
					this.OnDATAAREA_IDChanging(value);
					this.SendPropertyChanging();
					this._DATAAREA_ID = value;
					this.SendPropertyChanged("DATAAREA_ID");
					this.OnDATAAREA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIN_DEALER_ID", DbType="NVarChar(20)")]
		public string MAIN_DEALER_ID
		{
			get
			{
				return this._MAIN_DEALER_ID;
			}
			set
			{
				if ((this._MAIN_DEALER_ID != value))
				{
					this.OnMAIN_DEALER_IDChanging(value);
					this.SendPropertyChanging();
					this._MAIN_DEALER_ID = value;
					this.SendPropertyChanged("MAIN_DEALER_ID");
					this.OnMAIN_DEALER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_ID_MAPPING", DbType="NVarChar(20)")]
		public string SITE_ID_MAPPING
		{
			get
			{
				return this._SITE_ID_MAPPING;
			}
			set
			{
				if ((this._SITE_ID_MAPPING != value))
				{
					this.OnSITE_ID_MAPPINGChanging(value);
					this.SendPropertyChanging();
					this._SITE_ID_MAPPING = value;
					this.SendPropertyChanged("SITE_ID_MAPPING");
					this.OnSITE_ID_MAPPINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ACTIVE", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string IS_ACTIVE
		{
			get
			{
				return this._IS_ACTIVE;
			}
			set
			{
				if ((this._IS_ACTIVE != value))
				{
					this.OnIS_ACTIVEChanging(value);
					this.SendPropertyChanging();
					this._IS_ACTIVE = value;
					this.SendPropertyChanged("IS_ACTIVE");
					this.OnIS_ACTIVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_BY", DbType="NVarChar(10)")]
		public string CREATE_BY
		{
			get
			{
				return this._CREATE_BY;
			}
			set
			{
				if ((this._CREATE_BY != value))
				{
					this.OnCREATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATE_BY = value;
					this.SendPropertyChanged("CREATE_BY");
					this.OnCREATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIF_BY", DbType="NVarChar(10)")]
		public string MODIF_BY
		{
			get
			{
				return this._MODIF_BY;
			}
			set
			{
				if ((this._MODIF_BY != value))
				{
					this.OnMODIF_BYChanging(value);
					this.SendPropertyChanging();
					this._MODIF_BY = value;
					this.SendPropertyChanged("MODIF_BY");
					this.OnMODIF_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIF_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIF_DATE
		{
			get
			{
				return this._MODIF_DATE;
			}
			set
			{
				if ((this._MODIF_DATE != value))
				{
					this.OnMODIF_DATEChanging(value);
					this.SendPropertyChanging();
					this._MODIF_DATE = value;
					this.SendPropertyChanged("MODIF_DATE");
					this.OnMODIF_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MPM_DOORPRIZE")]
	public partial class MPM_DOORPRIZE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDOORPRIZE;
		
		private string _NAMA;
		
		private System.Nullable<int> _JUMLAH;
		
		private string _KETERANGAN;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _MODIFBY;
		
		private System.Nullable<System.DateTime> _MODIFDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDOORPRIZEChanging(int value);
    partial void OnIDDOORPRIZEChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnJUMLAHChanging(System.Nullable<int> value);
    partial void OnJUMLAHChanged();
    partial void OnKETERANGANChanging(string value);
    partial void OnKETERANGANChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnMODIFBYChanging(string value);
    partial void OnMODIFBYChanged();
    partial void OnMODIFDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFDATEChanged();
    #endregion
		
		public MPM_DOORPRIZE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDOORPRIZE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDOORPRIZE
		{
			get
			{
				return this._IDDOORPRIZE;
			}
			set
			{
				if ((this._IDDOORPRIZE != value))
				{
					this.OnIDDOORPRIZEChanging(value);
					this.SendPropertyChanging();
					this._IDDOORPRIZE = value;
					this.SendPropertyChanged("IDDOORPRIZE");
					this.OnIDDOORPRIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(100)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JUMLAH", DbType="Int")]
		public System.Nullable<int> JUMLAH
		{
			get
			{
				return this._JUMLAH;
			}
			set
			{
				if ((this._JUMLAH != value))
				{
					this.OnJUMLAHChanging(value);
					this.SendPropertyChanging();
					this._JUMLAH = value;
					this.SendPropertyChanged("JUMLAH");
					this.OnJUMLAHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KETERANGAN", DbType="VarChar(200)")]
		public string KETERANGAN
		{
			get
			{
				return this._KETERANGAN;
			}
			set
			{
				if ((this._KETERANGAN != value))
				{
					this.OnKETERANGANChanging(value);
					this.SendPropertyChanging();
					this._KETERANGAN = value;
					this.SendPropertyChanged("KETERANGAN");
					this.OnKETERANGANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(50)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFBY", DbType="VarChar(50)")]
		public string MODIFBY
		{
			get
			{
				return this._MODIFBY;
			}
			set
			{
				if ((this._MODIFBY != value))
				{
					this.OnMODIFBYChanging(value);
					this.SendPropertyChanging();
					this._MODIFBY = value;
					this.SendPropertyChanged("MODIFBY");
					this.OnMODIFBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFDATE
		{
			get
			{
				return this._MODIFDATE;
			}
			set
			{
				if ((this._MODIFDATE != value))
				{
					this.OnMODIFDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFDATE = value;
					this.SendPropertyChanged("MODIFDATE");
					this.OnMODIFDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MPM_DOORPRIZE_USER")]
	public partial class MPM_DOORPRIZE_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDUSER;
		
		private string _NPK;
		
		private string _NAMA;
		
		private string _DIVISI;
		
		private string _COMPANYOFFICE;
		
		private string _WORKLOCATION;
		
		private string _KETENTUANWARNA;
		
		private string _STATUSHADIR;
		
		private string _STATUSPEMENANG;
		
		private string _KODEHADIAH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUSERChanging(int value);
    partial void OnIDUSERChanged();
    partial void OnNPKChanging(string value);
    partial void OnNPKChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnDIVISIChanging(string value);
    partial void OnDIVISIChanged();
    partial void OnCOMPANYOFFICEChanging(string value);
    partial void OnCOMPANYOFFICEChanged();
    partial void OnWORKLOCATIONChanging(string value);
    partial void OnWORKLOCATIONChanged();
    partial void OnKETENTUANWARNAChanging(string value);
    partial void OnKETENTUANWARNAChanged();
    partial void OnSTATUSHADIRChanging(string value);
    partial void OnSTATUSHADIRChanged();
    partial void OnSTATUSPEMENANGChanging(string value);
    partial void OnSTATUSPEMENANGChanged();
    partial void OnKODEHADIAHChanging(string value);
    partial void OnKODEHADIAHChanged();
    #endregion
		
		public MPM_DOORPRIZE_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUSER", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDUSER
		{
			get
			{
				return this._IDUSER;
			}
			set
			{
				if ((this._IDUSER != value))
				{
					this.OnIDUSERChanging(value);
					this.SendPropertyChanging();
					this._IDUSER = value;
					this.SendPropertyChanged("IDUSER");
					this.OnIDUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPK", DbType="VarChar(5)")]
		public string NPK
		{
			get
			{
				return this._NPK;
			}
			set
			{
				if ((this._NPK != value))
				{
					this.OnNPKChanging(value);
					this.SendPropertyChanging();
					this._NPK = value;
					this.SendPropertyChanged("NPK");
					this.OnNPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISI", DbType="VarChar(50)")]
		public string DIVISI
		{
			get
			{
				return this._DIVISI;
			}
			set
			{
				if ((this._DIVISI != value))
				{
					this.OnDIVISIChanging(value);
					this.SendPropertyChanging();
					this._DIVISI = value;
					this.SendPropertyChanged("DIVISI");
					this.OnDIVISIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANYOFFICE", DbType="VarChar(50)")]
		public string COMPANYOFFICE
		{
			get
			{
				return this._COMPANYOFFICE;
			}
			set
			{
				if ((this._COMPANYOFFICE != value))
				{
					this.OnCOMPANYOFFICEChanging(value);
					this.SendPropertyChanging();
					this._COMPANYOFFICE = value;
					this.SendPropertyChanged("COMPANYOFFICE");
					this.OnCOMPANYOFFICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKLOCATION", DbType="VarChar(50)")]
		public string WORKLOCATION
		{
			get
			{
				return this._WORKLOCATION;
			}
			set
			{
				if ((this._WORKLOCATION != value))
				{
					this.OnWORKLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._WORKLOCATION = value;
					this.SendPropertyChanged("WORKLOCATION");
					this.OnWORKLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KETENTUANWARNA", DbType="VarChar(50)")]
		public string KETENTUANWARNA
		{
			get
			{
				return this._KETENTUANWARNA;
			}
			set
			{
				if ((this._KETENTUANWARNA != value))
				{
					this.OnKETENTUANWARNAChanging(value);
					this.SendPropertyChanging();
					this._KETENTUANWARNA = value;
					this.SendPropertyChanged("KETENTUANWARNA");
					this.OnKETENTUANWARNAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSHADIR", DbType="VarChar(50)")]
		public string STATUSHADIR
		{
			get
			{
				return this._STATUSHADIR;
			}
			set
			{
				if ((this._STATUSHADIR != value))
				{
					this.OnSTATUSHADIRChanging(value);
					this.SendPropertyChanging();
					this._STATUSHADIR = value;
					this.SendPropertyChanged("STATUSHADIR");
					this.OnSTATUSHADIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSPEMENANG", DbType="VarChar(50)")]
		public string STATUSPEMENANG
		{
			get
			{
				return this._STATUSPEMENANG;
			}
			set
			{
				if ((this._STATUSPEMENANG != value))
				{
					this.OnSTATUSPEMENANGChanging(value);
					this.SendPropertyChanging();
					this._STATUSPEMENANG = value;
					this.SendPropertyChanged("STATUSPEMENANG");
					this.OnSTATUSPEMENANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KODEHADIAH", DbType="VarChar(50)")]
		public string KODEHADIAH
		{
			get
			{
				return this._KODEHADIAH;
			}
			set
			{
				if ((this._KODEHADIAH != value))
				{
					this.OnKODEHADIAHChanging(value);
					this.SendPropertyChanging();
					this._KODEHADIAH = value;
					this.SendPropertyChanged("KODEHADIAH");
					this.OnKODEHADIAHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
